services:
  app:
    build: .
    container_name: nextjs-app
    user: root # Força o container a ter poder de escrita interno
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@db:5432/next_db?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
      # Estes volumes abaixo NÃO sincronizam com seu Mac, ficam só no Docker
      - /app/node_modules
      - /app/.next
      - /app/prisma/client

  # Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: nextjs-db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: next_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: